# Generated by Django 2.2.3 on 2021-04-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210405_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='address',
            field=models.CharField(default='3T4TwXEd', max_length=255, null=True, unique=True),
        ),
    ]
