# Generated by Django 2.2.3 on 2021-04-05 09:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210405_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='wallet_count',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='address',
            field=models.CharField(default='2163441549', max_length=255, null=True, unique=True),
        ),
    ]
