# Generated by Django 2.2.3 on 2021-04-05 09:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210405_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='address',
            field=models.CharField(default=uuid.uuid4, max_length=20, null=True, unique=True),
        ),
    ]
